### ISSUE TITLE
Regression in Test/IgnorePath/WithIgnorePathNoMatch

### ISSUE THREAD

**Issue by s-urbaniak** [brancz/kube-rbac-proxy#108]
We seem to fail consistently in FAIL: Test/IgnorePath/WithIgnorePathNoMatch, compare https://github.com/brancz/kube-rbac-proxy/runs/1790596451?check_suite_focus=true.

This seems to be introduced as part of https://github.com/brancz/kube-rbac-proxy/pull/104 but it might be a red herring as the e2e test there passed https://github.com/brancz/kube-rbac-proxy/runs/1569876652.

**Comment by s-urbaniak** [comment]
Strange, this seems to be green now https://github.com/brancz/kube-rbac-proxy/runs/1790930013?check_suite_focus=true

It _might_ be a flake then.

cc @paulfantom

**Comment by s-urbaniak** [comment]
The e2e tests seem to be flaky per se, now we have a failure in `FAIL: Test/AllowPath/WithPathAllowed` in the following run: https://github.com/brancz/kube-rbac-proxy/runs/1791026701?check_suite_focus=true

**Comment by paulfantom** [comment]
It looks to me like we might be starting tests [too soon after `kind load`](https://github.com/brancz/kube-rbac-proxy/blob/master/.github/workflows/build.yml#L66-L67). It might be good to first check if that image is available and the start tests plus make tests more resilient.

**Comment by s-urbaniak** [comment]
@paulfantom i think we have to dig deeper here, the patch didn't seem to help in a recent PR.

**Comment by s-urbaniak** [comment]
ok, i think i know what is going on. while tests are being executed, kube-rbac-proxy deployments are being deleted but we are not waiting until those instances are out of service interfering with subsequent tests.
