### ISSUE TITLE
kube-rbac-proxy keeps restarting

### ISSUE THREAD

**Issue by lechen26** [brancz/kube-rbac-proxy#109]
Hi

i have  GKE v1.17.14-gke.1600 with node-exporter:v0.18.1  and kube-rbac-proxy:v0.4.1.

recently node-exporter pods started to CrashLoopBack due to kube-rbac-proxy.
from the logs on the kube-rbac-proxy container i see the following:
```
I 2021-02-17T09:25:46.844609Z Generating self signed cert as no cert is provided 
I 2021-02-17T09:26:46.444021Z Starting TCP socket on [10.132.0.22]:9100 
F 2021-02-17T09:26:46.444366Z failed to listen on secure address: listen tcp 10.132.0.22:9100: bind: cannot assign requested address 
I 2021-02-17T09:26:50.245642Z Generating self signed cert as no cert is provided 
I 2021-02-17T09:27:36.644473Z Starting TCP socket on [10.132.0.57]:9100 
I 2021-02-17T09:27:36.644671Z Listening securely on [10.132.0.57]:9100 
I 2021-02-17T11:25:00.832301Z Generating self signed cert as no cert is provided 
I 2021-02-17T11:25:27.932392Z Starting TCP socket on [10.132.0.57]:9100 
F 2021-02-17T11:25:28.031565Z failed to listen on secure address: listen tcp 10.132.0.57:9100: bind: cannot assign requested address 
I 2021-02-17T11:25:32.433448Z Generating self signed cert as no cert is provided 
I 2021-02-17T11:26:06.232816Z Starting TCP socket on [10.132.0.62]:9100 
I 2021-02-17T11:26:06.331483Z Listening securely on [10.132.0.62]:9100 
I 2021-02-17T11:34:16.441464Z Generating self signed cert as no cert is provided 
I 2021-02-17T11:34:50.542939Z Starting TCP socket on [10.132.0.62]:9100 
F 2021-02-17T11:34:50.640542Z failed to listen on secure address: listen tcp 10.132.0.62:9100: bind: cannot assign requested address 
I 2021-02-17T11:34:53.743324Z Generating self signed cert as no cert is provided 
I 2021-02-17T11:35:21.040676Z Starting TCP socket on [10.132.0.36]:9100 
I 2021-02-17T11:35:21.040981Z Listening securely on [10.132.0.36]:9100 
I 2021-02-17T11:53:09.543923Z Generating self signed cert as no cert is provided 
I 2021-02-17T11:53:39.643516Z Starting TCP socket on [10.132.0.66]:9100 
I 2021-02-17T11:53:39.745283Z Listening securely on [10.132.0.66]:9100 
```

seems like it  tries to bind on port 9100 on the POD IP and failed to do that and keeps restarting and get new IP until it finally works.
any idea?

10x

**Comment by brancz** [comment]
Could it be that this happened after a rollout?

**Comment by lechen26** [comment]
i've checked further and seems like the underlying cause is the fact the underlying host was indeed preempted.
i have few node pools which are preemptible nodes and seems like this specific node was prermpted at the same time i saw the restart of the node-exporter pod.

the only issue i still see here, is the fact it got CrashloopBack and thats was related to the error
`failed to listen on secure address: listen tcp 10.132.0.62:9100: bind: cannot assign requested address`
until it was able to connect properly. 
maybe its also related to the fact the VM wasnt ready or there is a problem on this side?

10x!

**Comment by brancz** [comment]
My guess is that most likely for some reason two of the same pods were there (one of which was probably still terminating but still binding to the port, which caused this one not to be able to do so).

**Comment by lechen26** [comment]
checked further and based on the logs seems like the pod tried to  reach the OLD ip after preemption and once it failed it  tried again to the new IP and was able to do so.
so its probabaly the preemption process.

will check with GCP if that's expected, but doesnt seems related specifically to this service.
i guess you can close this issue.

10x for the major fast response :)
