### ISSUE TITLE
enhancement: static authorization

### ISSUE THREAD

**Issue by s-urbaniak** [brancz/kube-rbac-proxy#110]
To reduce api server load I suggest to implement a static authorization scheme. If configured, then:

1. token access reviews would still be performed towards API server
2. subject access reviews would not be issued but rather validated locally against a static configuration

According to @deads2k this helps tremendously in reducing API server load when kube-rbac-proxy is used in high-volume scraping targets like nodes (via node-exporter) or kubelets.

A prototype of a static authorizer is available for initial introspection of the idea at https://github.com/openshift/kube-rbac-proxy/pull/43/files.

The suggestion is to introduce a `static` array into the current configuration struct, i.e.:

```
type Config struct {
	Rewrites               *SubjectAccessReviewRewrites `json:"rewrites,omitempty"`
	ResourceAttributes     *ResourceAttributes          `json:"resourceAttributes,omitempty"`
	ResourceAttributesFile string                       `json:"-"`
	Static                 []StaticAuthorizationConfig   `json:"static,omitempty"`
}

type StaticAuthorizationConfig struct {
	User            UserConfig `json:"user,omitempty"`
	Verb            string     `json:"verb,omitempty"`
	Namespace       string     `json:"namespace,omitempty"`
	APIGroup        string     `json:"apiGroup,omitempty"`
	APIVersion      string     `json:"apiVersion,omitempty"`
	Resource        string     `json:"resource,omitempty"`
	Subresource     string     `json:"subresource,omitempty"`
	Name            string     `json:"name,omitempty"`
	ResourceRequest bool       `json:"resourceRequest,omitempty"`
	Path            string     `json:"path,omitempty"`
}

type UserConfig struct {
	Name   string   `json:"name,omitempty"`
	UID    string   `json:"uid,omitempty"`
	Groups []string `json:"groups,omitempty"`
}
```

This would then allow declaratively to enable static authorization for non-resource requests like so:
```
  config.yaml: |-
    "authorization":
      "static": [
        {
          "user":
            "name": "system:serviceaccount:monitoring:prometheus-k8s"
          "path": "/metrics"
          "verb": "get"
        }
      ]
```

The static authorizer could also be useful to enforce a rewrite. I.e. to authorize a static user and enforce authorization to a specific namespace one could configure:
```
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "namespace": "{{ .Value }}"
      "rewrites":
        "byQueryParameter":
          "name": "namespace"
      "static": [
        {
          "user":
            "name": "system:serviceaccount:monitoring:prometheus-k8s"
          "namespace": "my-namespace"
        }
      ]
```

I am happy to file a PR but was wondering if the maintainers have overall objections of adding such a functionality here.

cc @simonpasquier @brancz @paulfantom @lilic @deads2k

**Comment by brancz** [comment]
I like it :+1:

**Comment by deads2k** [comment]
I recommend removing `APIVersion      string     `json:"apiVersion,omitempty"``.  All versions of a group.resource tuple are expected to be semantically equivalent.  That's why RBAC doesn't have it.

I would skip user.uid since no standard authorizer uses it.

The idea of a local authorization policy in addition to delegation seems like a good idea.
