### ISSUE TITLE
Pass Authorization header with bearer token to upstream app

### ISSUE THREAD

**Issue by sparkoo** [brancz/kube-rbac-proxy#114]
Is there a way in kube-rbac-proxy to pass Authorization header with bearer token to the upstream application? I can see only option to pass user and groups, but not whole authorization header. I guess it's removed by apiserver authentication https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/request/bearertoken/bearertoken.go#L58

If it is really not possible at the moment, would you be interested in this contribution? Are there any security issues with it?

**Comment by sparkoo** [comment]
I've created draft PR to this https://github.com/brancz/kube-rbac-proxy/pull/115

**Comment by sparkoo** [comment]
cc: @brancz

**Comment by brancz** [comment]
I don't currently have much time for this project. Maybe @s-urbaniak can have a look?

**Comment by deads2k** [comment]
The idea of the kube-rbac-proxy is to handle the details of authentication and authorization for an application that is not kube-aware.  Passing a bearer token through to the upstream application itself implies that application knows how to handle kube credentials.  If that is the case it is more appropriate for the upstream application to terminate authn/authz itself using the k8s.io/apiserver library and DelegatingAuthentication/AuthorizationOptions.

The current behavior keeps the separation of concerns and matches the expectations of a terminating, authenticating proxy.

**Comment by s-urbaniak** [comment]
I agree with @deads2k here. It seems your use case does not need kube-rbac-proxy in the first place so exposing your application directly seems the better way forward.

**Comment by sparkoo** [comment]
I see your point @deads2k @s-urbaniak . However, it not possible in our use-case, because we don't control the upstream application. We're evaluating kube-rbac-proxy in Eclipse Che, which is kubernetes native IDE. We're running user's workspaces, which are composed of multiple containers (editor, plugins, language servers, tooling, ...) and possibly user's containers. And we want to secure that with authorization. At the same time, for some tooling in the user's workspace we need access to kubernetes cluster (e.g. to get some configuration/secrets etc.) and for that we need the token.

Reimplement and contribute authorization bits to all toolings upstreams would be very difficult if not impossible. It would be very painful to maintain and to include new tooling into the loop.
