### ISSUE TITLE
Support client certificate authenticated upstreams

### ISSUE THREAD

**Issue by cehoffman** [brancz/kube-rbac-proxy#128]
One usecase we have to transform the client certificate authenticated upstream
into a bearer token authenticated endpoint in order to avoid having to
distribute the client certificates, and instead rely on kubernetes service
accounts for the distribution.

**Comment by brancz** [comment]
I think this generally makes sense.

cc @s-urbaniak

**Comment by s-urbaniak** [comment]
@cehoffman that idea sounds good to me as well :+1: I image having `--upstream-client-cert-file`/`--upstream-client-key-file` options which specify the client cert key material. Do you want to give it a try? Happy to review the PR :-)

**Comment by ibihim** [comment]
Greetings from 2023! I came across this issue and have decided to proactively close it for now.

However, if you or anyone else still find this feature to be desired and relevant, please don't hesitate to reopen the issue, and we can continue the conversation. We appreciate your input and remain committed to addressing the needs and priorities of our users.

Thank you for your understanding, and we look forward to collaborating with you in the future.
