### ISSUE TITLE
Split up `func main`

### ISSUE THREAD

**Issue by ibihim** [brancz/kube-rbac-proxy#153]
## What

I would like to ask, kindly, if I might split up the `func main` in smaller functions that are logically connected. I wouldn't split the `run.Group` logic as it is not a good idea to separate that, but the rest has a lot of potential.

## Why

A lot of things are going on in the `func main` and I thought it would help me to digest it with less mental load, when chunked logically. I don't need it anymore after the exercise, but wondered if it could be beneficial for others.

## Note

I hope no one feels offended and thank you for taking your time to review this issue.

**Comment by s-urbaniak** [comment]
feel free to refactor, PRs are certainly welcome :-)
