### ISSUE TITLE
Please create tag/release for recent changes on the repo

### ISSUE THREAD

**Issue by rbranche** [brancz/kube-rbac-proxy#158]
Please create tag/release for recent changes on the repo since last release (0.11.0 on August 2):

#140 
#141 
#144 
#147 
#149 
#150

**Comment by rbranche** [comment]
cc @s-urbaniak @paulfantom @brancz @jan--f

**Comment by s-urbaniak** [comment]
@ibihim is in the process of creating a release

**Comment by strzonnek** [comment]
> @ibihim is in the process of creating a release

any update on the release?
The CVEs fixes are quite important.
Thanks, Stephan

**Comment by s-urbaniak** [comment]
once https://github.com/brancz/kube-rbac-proxy/pull/160 lands, there will be a new release prepared.

**Comment by strzonnek** [comment]
@s-urbaniak as [#160](https://github.com/brancz/kube-rbac-proxy/pull/160) has been merged, will there be a release in the near future? 
Regards, Stephan

**Comment by ibihim** [comment]
Yes, we want to do that. We will also like to take a quick look into https://github.com/brancz/kube-rbac-proxy/issues/163, if we should take it into the release.

**Comment by ibihim** [comment]
@strzonnek, v0.v12 is out.

**Comment by strzonnek** [comment]
> @strzonnek, v0.12.0 is out. Can we close the issue?

sure, thanks for your efforts!
Regards, Stephan

**Comment by ibihim** [comment]
Ok, so I will close it. I hope we will do it more regularly now. If I am missing anything, just reopen and tag me :smile:
