### ISSUE TITLE
Installation via Helm

### ISSUE THREAD

**Issue by christianknell** [brancz/kube-rbac-proxy#182]
Are there any plans for a Helm Chart?

**Comment by ibihim** [comment]
We don't have anything like that on our agenda yet. Currently we focus on maintaining and pushing the project closer towards the k8s sig-auth organization.

**Comment by ibihim** [comment]
As kube-rbac-proxy is running as a side-car it would be kinda tricky to offer it as a helm chart.
How would such a thing look like?
Most popular applications in combination with kube-rbac-proxy?

**Comment by christianknell** [comment]
You're absolutely right, that it doesn't really make sense to offer a Helm chart. Maybe it would make sense to provide everything you need if you want to include kube-rbac-proxy into an existing Helm chart? For example which values to define in values.yaml, how to adapt the pod definition, ...

**Comment by ibihim** [comment]
If you would like to have some possible starter values, we have an examples folder. We don't plan to offer Helm templates. If there are any questions, please reopen the issue.
