### ISSUE TITLE
Docs say "glog" is used, but now uses klog

### ISSUE THREAD

**Issue by ringerc** [brancz/kube-rbac-proxy#208]
The README.md still points to https://github.com/golang/glog for logging config, but the code seems to use klog now.

**Comment by ibihim** [comment]
> The kube-rbac-proxy has all [glog](https://github.com/golang/glog) flags for logging purposes.

It is claimed that it has the same flags as glog, not that it uses glog.
I will close the issue. Feel free to reopen it, if there are more questions.
