### ISSUE TITLE
program is stuck in the stop state

### ISSUE THREAD

**Issue by lovelly** [brancz/kube-rbac-proxy#220]
![image](https://user-images.githubusercontent.com/13118848/209609227-f0f4c626-6afd-4744-9d5d-4d91f358501f.png)
The program is always in the T state, causing Recv-Q to be full
![image](https://user-images.githubusercontent.com/13118848/209609513-af2c0c09-43de-4976-8d67-50c679dcacdd.png)

**Comment by ibihim** [comment]
Yes, please. We are eager to help based on logs. It is really hard to debug based on screenshots, especially when they are aggressively cropped.

**Comment by stlaz** [comment]
/close
not actionable

**Comment by ibihim** [comment]
@lovelly, please reopen with appropriate logs. Thank you
