### ISSUE TITLE
Request for moving this project repo under kubernetes-sigs 

### ISSUE THREAD

**Issue by droot** [brancz/kube-rbac-proxy#23]
We ([Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) team) are planning to use `kube-rbac-proxy` for adding authn/authz support to the metrics endpoint exposed by the controllers written using Kubebuilder. We would like to avoid forking the repo and maintaining our own container images. 

kube-rbac-proxy is a very useful project and having the repo and the container images available under kubernetes will benefit other OSS projects.  Have you considered it moving it under `kubernetes-sigs` ?

**Comment by mcristina422** [comment]
Was there any progress made in turning this into a SIG project? I'm definitely in support of this

**Comment by brancz** [comment]
I'd still like to make this happen and there were no objections when I last attended sig-auth, I just haven't had the time to follow up on it.

**Comment by camilamacedo86** [comment]
HI folks, 

@brancz @droot do we have any updates on this one?

**Comment by metalmatze** [comment]
I know that it was recently (Feb 2nd) discussed in SIG Auth: https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#
cc @s-urbaniak & @ibihim

**Comment by ibihim** [comment]
@camilamacedo86, we pitched it to sig-auth again (on the 2nd of Feburary, 2022) and the process started. Currently we have a review as a first next step:

https://github.com/brancz/kube-rbac-proxy/pull/162

**Comment by ibihim** [comment]
I created two issues that track tasks that need to be done:
https://github.com/brancz/kube-rbac-proxy/issues/168
https://github.com/brancz/kube-rbac-proxy/issues/169

I will close this issue within a month, if no one complains, as the task 169 should reflect the progress more or less accurately.

**Comment by ibihim** [comment]
I will close the issue as being stale. Feel free to reopen it, if it is still an issue.
