### ISSUE TITLE
Cut a new release with golang version 1.20

### ISSUE THREAD

**Issue by ameypant13** [brancz/kube-rbac-proxy#239]
golang version is bumped to 1.20 and merged to master. Can you cut a new release?

**Comment by ibihim** [comment]
https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.14.2

**Comment by vasireddy99** [comment]
@ibihim Sorry for pinging here, Are these kube-rbac-images are not released in [gcr.io](https://console.cloud.google.com/gcr/images/kubebuilder/global/kube-rbac-proxy) anymore. Just trying to understand.
