### ISSUE TITLE
Token Auth is fine, but User Auth (cert) is not processed

### ISSUE THREAD

**Issue by mrrandrade** [brancz/kube-rbac-proxy#24]
Hey there.

If I understood it right, kube-rbac-proxy works with both token (ServiceAccount directive on RBAC) and signed certificates (User directive on RBAC). I'm having trouble AUTH'ing with just certs.

> This proxy was developed in order to restrict requests to only those Pods, that present a valid and RBAC authorized token or client TLS certificate.

Just deployed kube-rbac-proxy as a sidecar to a prometheus-node-exporter. Plan is to protect the /metrics endpoint.

Followed the example, everything is fine enough:

```
# TOKEN=$( cat /var/run/secrets/kubernetes.io/serviceaccount/token )
# curl -k --header "Authorization: Bearer $TOKEN" https://kubernetes-node:9100/metrics
go_gc_duration_seconds{quantile="0"} 4.3349e-05
...
```
I enabled verbose loggin to see what it does. When I try with tokens like the line above, a lot of messages are generated:

```
POST https://master.kubernetes/apis/authentication.k8s.io/v1beta1/tokenreviews 
...
POST https://master.kubernetes/apis/authorization.k8s.io/v1beta1/subjectaccessreviews 201 Created in 2 milliseconds
```  
When I try with a simple CA signed certificate with curl it generates no message, and gives me 'Unauthorized':

```
# curl -k https://kubernetes-node:9100/metrics --cert ./tls.crt --key ./tls.key --cacert ./tls.ca
Unauthorized
```
No logs at all are generated.

I made sure I'm using the correct certificates and set this parameter:
```
      - --client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

```
cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | openssl x509 -noout -subject
subject= /CN=X-Homologacao

openssl x509 -in ./tls.ca | openssl x509 -noout -issuer 
issuer= /CN=X-Homologacao
```

My master is protected by that very same CA:
```
# systemctl cat kube-apiserver.service
...
--client-ca-file=/etc/kubernetes/ssl/ca.pem
...

# md5sum /etc/kubernetes/ssl/ca.pem
2e03ecc30fe8f662760781a59a5941c0  /etc/kubernetes/ssl/ca.pem
# md5sum /var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
2e03ecc30fe8f662760781a59a5941c0  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

```
My curl with certs to him works just fine:

```
curl -k https://master.hom.estaleiro.serpro:443/api --cert tls.crt --key ./tls.key --cacert ./tls.ca
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
...
```
Am I doing this wrong or is it a bug?

**Comment by brancz** [comment]
I'm about to go on vacation, so @metalmatze @s-urbaniak can you have a look at this?

**Comment by s-urbaniak** [comment]
@mrrandrade sorry for the late answer, but vacations delayed this a lot. Just quickly looking at the code I don't see any obvious bug here (although that doesn't mean there is none), but just to verify.

Looking at the client certificate mapping code:
https://github.com/brancz/kube-rbac-proxy/blob/4109f9915c59048db507b4d6c5e2f70504b95716/vendor/k8s.io/apiserver/pkg/authentication/request/x509/x509.go#L182-L192

Does the user/group associated with the client certificate's common name/organization have the same rolebinding as the serviceaccount? As your client returns `Unauthorized` we might have a different problem, but I want to make sure first there is no misconfig in the role binding.

In the meanwhile I'll try to reproduce this myself.

**Comment by mrrandrade** [comment]
Hey guys! OP here! How you doing? It's been a while.

I want to drop the solution I used in favour of kube-rbac-proxy and I'm trying once again, now with the new version! 

Unfortunately I still can't get certs to work. Using 0.6.0.

**Short Version**:

I was 99,9% inclined to say that kube-rbac-proxy is dropping my connection without even trying because it doesn't recognize my cert's CA because:

```
# No certs at all:
curl -k https://10.99.2.5:8069/metrics
Unauthorized

# My certs:
curl -sk --cacert ./tls.ca --cert ./tls.crt --key ./tls.key https://10.99.2.5:8069/metrics
Unauthorized
```

Unfortunately not even with the http port it works:

```
# Kube-rbac-proxy with - --insecure-listen-address=0.0.0.0:8080
curl -k http://10.99.2.5:8080/metrics
Unauthorized
```

Also, no logs whatsoever, even with -v10.

So I honestly have no idea.

---

**Long Version**!

I have an SA and the user above (06946844469, yeah, username is only numbers, i know, it sucks, not my choice though.)

# openssl x509 -in tls.crt -noout -subject
# openssl x509 -in tls.crt -noout -subject | fgrep 06946844469
subject= /O=system:masters/CN=06946844469

**Test 1**: token: ok!

```
# curl -sk -H "Authorization: Bearer ${TOKEN}" https://10.99.2.5:8069/metrics | tail -n1
promhttp_metric_handler_requests_total{code="503"} 0
```

**Test 2**: certs: nok.

```
# curl -sk --cacert ./tls.ca --cert ./tls.crt --key ./tls.key https://10.99.2.5:8069/metrics
Unauthorized
```

**Debug 1**:  Maybe the cert is wrong:

```
# # Exact same command, access Kubernetes API fine:
# curl -sk --cacert ./tls.ca --cert ./tls.crt --key ./tls.key https://10.99.2.0:6443/api/v1/namespaces/default | jq -r '.metadata.name'
```

**Debug 2**: maybe RBAC is wrong? Point asked by s-urbaniak: 

> Does the user/group associated with the client certificate's common name/organization have the same rolebinding as the serviceaccount? 

Owner of the cert:
```
# openssl x509 -in tls.crt -noout -subject | fgrep 06946844469
subject= /O=system:masters/CN=06946844469
```
RBAC that allows both token and user to access /metrics:

```
kubectl neat get clusterrolebinding estaleiro:monitoring-client -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: estaleiro:monitoring-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: estaleiro:monitoring-client
subjects:
- kind: ServiceAccount
  name: estaleiro-monitoring-client
  namespace: kube-system
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "06946844469"
```

---

Stuff I tried:

* Using --client-ca-file pointing to the CA that signed the certs (same CA that generated all Kubernetes certs):
```
       - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
```

* Used kube-rbac-proxy with custom certs signed by the Kubernetes CA:
```
        - --tls-cert-file=/etc/tls/tls.crt
        - --tls-private-key-file=/etc/tls/tls.key
```
* tried last config with and without client-ca-file.

As I mentioned at the short version, server doesn't even try to validate my user, so it doesn't create a review for it (actually it doesn't even log).

**Comment by ibihim** [comment]
This is a stale issue. If there is no request for keeping it open within a month, I would like to close it.

**Comment by ibihim** [comment]
I will close the issue as being stale. Feel free to reopen it, if it is still an issue.
