### ISSUE TITLE
Twistlock reporting CVE PRISMA-2022-0227 

### ISSUE THREAD

**Issue by oziel88** [brancz/kube-rbac-proxy#245]
Proposal

Hello, 

Our TwistLock scan is reporting this CVE below:

| CVE  | SEVERITY | CVSS | PACKAGE | VERSION | STATUS | DESCRIPTION |
| -------------------- | ------------- | ---- | ---- | ---- | ---- | ---- | 
| PRISMA-2022-0227 | high | 7.50  | github.com/emicklei/go-restful/v3 | v3.8.0 | fixed in v3.10.0 | github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system |

Can this be remediated in next release?

Thank you

**Comment by ibihim** [comment]
Yes, we can do that.

Disclaimer: 
As this code path is not used by us (emicklei/go-restful), it is not a super high priority for us. If we encounter a real CVE, we would do everything in our power to fix it asap.

**Comment by ibihim** [comment]
Should be fixed with https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.14.3
