### ISSUE TITLE
kube-rbac-proxy failing authentication and authorization intermittently with error:

### ISSUE THREAD

**Issue by MohitBairagi** [brancz/kube-rbac-proxy#247]
I am using kube-prometheus-stack for cluster monitoring and node-exporter is also one of the monitoring component  in the setup. node-exporter is running inside a pod with kube-rbac-proxy container. 
But what I have seen sometimes kube-rbac-proxy works and node-exporter data shows in prometheus targets and sometimes it fails with following error:

`
E0705 06:18:03.897282 1167454 auth.go:47] Unable to authenticate the request due to an error: [invalid bearer token, service account token is not valid yet]
E0705 06:18:16.608326 1167454 auth.go:47] Unable to authenticate the request due to an error: [invalid bearer token, service account token is not valid yet]
E0705 06:18:19.287587 1167454 auth.go:47] Unable to authenticate the request due to an error: [invalid bearer token, service account token is not valid yet]
E0705 06:18:31.605597 1167454 webhook.go:154] Failed to make webhook authenticator request: Unauthorized
E0705 06:18:31.605670 1167454 auth.go:47] Unable to authenticate the request due to an error: Unauthorized
E0705 06:18:33.896354 1167454 webhook.go:154] Failed to make webhook authenticator request: Unauthorized
E0705 06:18:33.896484 1167454 auth.go:47] Unable to authenticate the request due to an error: Unauthorized
E0705 06:18:46.605123 1167454 webhook.go:154] Failed to make webhook authenticator request: Unauthorized
E0705 06:18:46.605195 1167454 auth.go:47] Unable to authenticate the request due to an error: Unauthorized
`

**Comment by ibihim** [comment]
Closing due to lack of response, if there is a follow up, feel free to reopen.
