### ISSUE TITLE
Support workloads with http probes

### ISSUE THREAD

**Issue by serathius** [brancz/kube-rbac-proxy#25]
To secure application using kube-rbac-proxy application needs to bind on localhost. In cases when pod is not running in host network, application is not reachable for kubelet to perform healthchecks. 
To my knowledge there is no way to configure kubelet to use service account tokens when performing http probes, making it impossible to use kube-rbac-proxy with healthchecks without adding yet another proxy just for them. 

I see two possible ways to solve it:
* authorize kubelet http probe to "/healthz" (not sure if it's possible, could be risky to allow access nonResourceURLs on all pods)
* Allow to skip authorization for whitelisted endpoints in kube-rbac-proxy

**Comment by brancz** [comment]
> Allow to skip authorization for whitelisted endpoints in kube-rbac-proxy

This seems like a reasonable thing to me as explicit flags on kube-rbac-proxy.
