### ISSUE TITLE
Image of kube-rbac-proxy new version (v0.14.3) wasn't pushed to quay.io repository

### ISSUE THREAD

**Issue by ShacharMalachi** [brancz/kube-rbac-proxy#255]
Hi,

I've seen you released a new version that fixed few security vulnerabilities, just letting you know that image wasn't pushed to quay.io repository ([https://quay.io/repository/brancz/kube-rbac-proxy?tab=tags](https://quay.io/repository/brancz/kube-rbac-proxy?tab=tags)), probably because **"Go / Publish container image to Quay (push)"** step failed for some reason.

Can you please push this new image to quay.io repository?

Thanks!
Shachar.

**Comment by ibihim** [comment]
Hi, thanks for the notification, I will check what went wrong!

**Comment by jhongturney** [comment]
@ibihim I've proposed a fix here: https://github.com/brancz/kube-rbac-proxy/pull/256

**Comment by ibihim** [comment]
@jhongturney, thx for your efforts. The build system is pretty bridle. I re-do it at some point.

The fix looks like this: https://github.com/brancz/kube-rbac-proxy/pull/258.

The change I did to make `kube-rbac-proxy --version` work, broke the `scripts/publish.sh` as it started to append the shortened git commit hash, always.

**Comment by ibihim** [comment]
The images are released. If there are any issues, please reopen.

Sorry for any inconveniences caused. I will watch the creation of the images next time to spot issues quicker.
