### ISSUE TITLE
Failing to instantiate OIDC authenticator when --oidc-ca-file is not specified

### ISSUE THREAD

**Issue by nickytd** [brancz/kube-rbac-proxy#259]
Hi, 

According to the description of [oidc-ca-file](https://github.com/brancz/kube-rbac-proxy/blob/3ed1e58004ea4bcb493d22addec89aa50d4a10e1/cmd/kube-rbac-proxy/app/options/options.go#L111) parameter, is optional. When it is not specified it shall fallback to the `/etc/ssl/certs/ca-certificates.crt`. The latter is part of the distro-less base image. However the current implementation, using the `k8s.io/apiserver/pkg/server/dynamiccertificates` https://github.com/kubernetes/apiserver/blob/v0.28.2/pkg/server/dynamiccertificates/dynamic_cafile_content.go#L76,  returns an error instead of fallback
```
E0920 14:13:37.375979       1 run.go:74] "command failed" err="failed to instantiate OIDC authenticator: missing filename for ca bundle"
```
The simplest possible fix would be to just set the default as described in the documentation
```
// NewOIDCAuthenticator returns OIDC authenticator
func NewOIDCAuthenticator(config *OIDCConfig) (*OIDCAuthenticator, error) {
	if config.CAFile == "" {
		//If the CA file is not defined, it shall default to the host system trusted ca bundle
		config.CAFile="/etc/ssl/certs/ca-certificates.crt"
	}
	dyCA, err := dynamiccertificates.NewDynamicCAContentFromFile("oidc-ca", config.CAFile)
	if err != nil {
		return nil, err
	}
...
```
Here is  a PR in case you confirm the problem and agree with the solution proposal.

Thanks
Niki

**Comment by ibihim** [comment]
Wouldn't it be better to specify `--oidc-ca-file=/etc/ssl/certs/ca-certificates.crt`?

This is also a very specific path: There are at least [4 different paths in Linux distributions](https://github.com/FiloSottile/mkcert/blob/master/truststore_linux.go#L36C2-L48).

I am not completely convinced that the added complexity is worth it, but I might be missing context.

**Comment by nickytd** [comment]
The `default` location is based on the base image `gcr.io/distroless/static:nonroot`. I guess `mkcert` needs to consider all those options as it shall run/support different env. In the case here, the base image is not a moving part or at least we know the exact env on which the `kube-rbac-proxy` needs to run. It can check a set of 'default' locations but we always know which one will be used at the end. IMHO it is a fair trade off.

**Comment by ibihim** [comment]
In the context of the original image, yes, there is just one, but a lot of organizations repackage the image AFAIK.
Also I would bind myself to an image / distro. I am really hesitant about that. I gave the example of `mkcert` as I was curious how they manage different possibilities.

E.g. bitnami uses mini-debian? kubebuilder seems to do some repackging too?

I can reach out for a second opinion to other maintainers.

**Comment by nickytd** [comment]
Yep it is a valid case. Different distributions manage the case differently. Just for a reference here are some links:
- [RedHat](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-shared-system-certificates) 
- [Debian](https://manpages.debian.org/buster/ca-certificates/update-ca-certificates.8.en.html)
- [openSuSE](https://github.com/openSUSE/ca-certificates/blob/master/README)
Probably these locations can also change with new releases, but still a set of default locations can be compiled, taking care for the majority of the cases. No objections at all.

**Comment by ibihim** [comment]
I talked to @s-urbaniak and he wasn't convinced either. I hope you are not disappointed.

Thx for your frequent contributions.

**Comment by nickytd** [comment]
@ibihim No not at all. The project owners/maintainers decide on if or how to solve cases.

**Comment by dimityrmirchev** [comment]
Hi @nickytd , @ibihim 

The underlying package handles the case when `opts.CAContentProvider == nil` so if the `--oidc-ca-file` is not set then the CA Content Provider can be left as `nil` which will cause the authenticator to use the host's root CA. This I think is a good solution which will not hardcode any distro specific paths. I can open a PR if this work for you.

Here is the reference code:
https://github.com/kubernetes/kubernetes/blob/2b472fe4690c83a2b343995f88050b2a3e9ff0fa/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go#L282-L301

**Comment by ibihim** [comment]
Hm, yes. If this is idiomatic k8s behavior, it is fine.
