### ISSUE TITLE
Compability with new K8S versions

### ISSUE THREAD

**Issue by yjian118** [brancz/kube-rbac-proxy#272]
Since the last issue was closed a long time ago, I want to check the compatibility of newer versions of the k8s cluster(v1.26-v1.28).
Further, it would be great if we could maintain a compatibility table.

**Comment by ibihim** [comment]
If there are any compatibility issues, you can report them and I will investigate them.

Usually kube-rbac-proxy is tested against the kubernetes setup given by kind. In particular, the test run is pointing at a kubernetes version v1.28.4.

I don't have the capacity to maintain a compatibility table. As this is open source, you can contribute such a table.

**Comment by ibihim** [comment]
As there is no follow up, I will close this issue.
