### ISSUE TITLE
Can kube rbac proxy be used for kubeedge?

### ISSUE THREAD

**Issue by thinkeng** [brancz/kube-rbac-proxy#273]
Can kube rbac proxy be used for kubeedge? I reported the following error while using it

`E1219 11:20:05.546400  943991 run.go:74] "command failed" err="failed to load kubeconfig: cannot find Service Account in pod to build in-cluster rest config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"`

**Comment by ibihim** [comment]
I can't say much about KubeEdge as I don't have any experience with it.

Failed to load kubeconfig happens, when it can't find a kubeconfig. It uses to look at well known places for it otherwise it needs to be specified with the `--kubeconfig` flag.

**Comment by Mengxue12** [comment]
> I can't say much about KubeEdge as I don't have any experience with it.
> 
> Failed to load kubeconfig happens, when it can't find a kubeconfig. It uses to look at well known places for it otherwise it needs to be specified with the `--kubeconfig` flag.
> 
> This happens if you try to run kube-rbac-proxy outside of a Pod / k8s.io environment, like your local machine. Providing the path to the kubeconfig fixes it.

Thank you. I had the same problem and fixed it by using `--kubeconfig` flag.
But I have a question, this config need the read access, but then i have this warning: ` Kubernetes configuration file is group-readable. This is insecure. ` may i ask if there's better way to solve this?
