### ISSUE TITLE
Multi Arch Image pulled from quay.io does not work in arm64/graviton nodes

### ISSUE THREAD

**Issue by santhotech** [brancz/kube-rbac-proxy#275]
Hi 

I pulled the image quay.io/brancz/kube-rbac-proxy:v0.14.2 and 0.15.0. Inspected the images to verify they are multi-arch and they contain the digests for all supported archs in their manifest. However, when I run the container on an EKS Cluster with Graviton/ARM64 nodes, the container fails to start with the "exec; error wrong format" error. Upon swapping the graviton nodes for amd nodes, the container runs fine. 

Our expectation was that this multi-arch image should run regardless of arm/amd arch. Am I missing something or could this be a defect in how this image was built?

**Comment by ibihim** [comment]
Yes, the digest part is pretty odd, I see it here too: [kube-rbac-proxy on quay.io](https://quay.io/repository/brancz/kube-rbac-proxy?tab=tags&tag=latest).

I didn't set up the pipelines, but from what I see in the [Makefile](https://github.com/brancz/kube-rbac-proxy/blob/master/Makefile#L61-L63) the image without a suffix is just an amd64 image..

**Comment by santhotech** [comment]
Thanks @ibihim  for the confirmation, short of re-building the image to be multi-arch, do you have any recommendation for a work around?

**Comment by ibihim** [comment]
So you have a requirement to have a multi arch image?

As it is open source, you can contribute to the project.

**Comment by ibihim** [comment]
As there is no follow up, I will close the issue. If you have any concerns, feel free to reopen.
