### ISSUE TITLE
Upgrade go-jose to v4

### ISSUE THREAD

**Issue by octotocat** [brancz/kube-rbac-proxy#304]
New vulnerability of using go-jose.v2
https://github.com/advisories/GHSA-c5q2-7r4c-mv6g

**Comment by ibihim** [comment]
I was on vacation for 3 weeks. Will make an update. Thx for letting me know.

**Comment by ibihim** [comment]
Upstream didn't fix it, so I went for a replacement directive. I hope it works as expected:

https://github.com/brancz/kube-rbac-proxy/pull/309

**Comment by octotocat** [comment]
Thank you so much for the prompt support!
