### ISSUE TITLE
Serviced accounts blocked in mirror pods

### ISSUE THREAD

**Issue by StanYago** [brancz/kube-rbac-proxy#49]
Use of ServiceAccounts is blocked in static (mirror) pods such as kube-scheduler.  How can kube-rbac-proxy be used in this case?  There is mention of using certificates for authentication, but kube-rbac-proxy fails /w main.go:329] cannot find Service Account in pod to build in-cluster rest config

**Comment by brancz** [comment]
The kube-scheduler has the functionality provided by the kube-rbac-proxy basically built in, why do you need it there?

**Comment by StanYago** [comment]
kube-controller-manager and kube-scheduler's metrics endpoint is not protected.  With hostNetworking enabled, they will either listen on host's interface or on loopback interface.  In the first case it is exposed outside of cluster in the second it is not reachable by prometheus operator.  The CIS guidelines 1.2.2 and 1.3.7 recommend using the loopback interface.

**Comment by brancz** [comment]
Using kube-rbac-proxy to forward requests to loopback doesn’t improve the security story, it will still be exposed. Upstream secure endpoints offer the same features now as kube RBAC proxy will by forwarding to loopback.

**Comment by StanYago** [comment]
If there was a way to create authentication for https endpoints that is limited to /metrics only, then I must have missed it.

**Comment by brancz** [comment]
What other endpoints are there on the scheduler? And the RBAC role is exactly the same, being the non-resource-url /metrics :)

**Comment by pickledrick** [comment]
> Using kube-rbac-proxy to forward requests to loopback doesn’t improve the security story, it will still be exposed. Upstream secure endpoints offer the same features now as kube RBAC proxy will by forwarding to loopback.

Hi @brancz do you know of any documentation around this. I'm not following how the static pod `kube-scheduler` for example, if bound to a loopback address can receive network communication to perform a SAR?

**Comment by brancz** [comment]
The scheduler uses its certificate to communicate with the apiserver to perform the SAR. See this blog post: https://octetz.com/posts/secure-port-k8s-cm-sched

**Comment by StanYago** [comment]
The final missing part to get kube-scheduler working /w apiserver when using kubeadm
https://github.com/kubernetes/kubeadm/issues/1285#issuecomment-494476555
