### ISSUE TITLE
Not able to authenticate by kube rbac proxy

### ISSUE THREAD

**Issue by gayathrimenathtcl** [brancz/kube-rbac-proxy#51]
I am developing an admission controller which is protecting by kube rbac proxy. I have admission controller on '/' endpoint and prometheus metrics on '/metrics' endpoint. I am able to get the prometheus metrics data using the bearer token, but getting authentication error on admission controller. The authentication is expecting either a bearer token but the request doesn't contain token. How can I make a kube rbac proxy which prometheus metrics and admission controller endpoint will be available?

**Comment by brancz** [comment]
I assume the apiserver uses TLS client cert authentication? So you're saying you want to use both bearer token auth and TLS client cert auth right? If that doesn't work, then we should make that work :)

**Comment by gayathrimenathtcl** [comment]
Either bearer token or ca alone will work. 
I have some updates on this issue. The admission controller is to validate a yaml before applying it. I have enabled TLS as [https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers](kubernetes documentation).  The error occuring from kube-apiserver is

> error when creating "test.yaml": Internal error occurred: failed calling webhook "test.testns.svc": tls: failed to find any PEM data in certificate input
 The api server is not able to get the PEM certificates. While logging, I am able to see the some data but which is not in PEM format/readable format.

**Comment by brancz** [comment]
I see, so you're saying both should work at the same time, but if webhook authentication is enabled, then only webhook authentication is possible. That would indeed be a bug I think that we should fix.
