### ISSUE TITLE
Does it supports HTTPS?

### ISSUE THREAD

**Issue by sachinmsft** [brancz/kube-rbac-proxy#58]
From the documentation it seems that it provides the authorization and authentication of the client(Prometheus in this case) but does not provide the end to end TLS communication encryption. 
Is my understanding correct ?

**Comment by brancz** [comment]
I'm not sure what you mean by end to end TLS communication encryption. kube-rbac-proxy is perfectly capable of serving traffic via TLS and verify client certificates if that's what you are asking.

**Comment by sachinmsft** [comment]
Thanks @brancz . When I read the documentation I understood that this proxy is only capable of doing authentication and authorization of the connection initiated pod.
what server certificate it uses for TLS ? I don't see any certificate generation steps anywhere.

**Comment by sachinmsft** [comment]
Seems It takes 
--tls-cert-file string                        
--tls-cipher-suites strings                   
--tls-min-version string                      
--tls-private-key-file string  

parameters and we can create and provide the server cert and private key to support HTTPS 
is my understanding correct ?

**Comment by sachinmsft** [comment]
Though I don't see that server cert is being passed in Kube-Prometheus project https://github.com/coreos/kube-prometheus/blob/master/manifests/node-exporter-daemonset.yaml#L45

**Comment by brancz** [comment]
When no cert is specified but a secure listen address is passed as a flag then kube rbac proxy generates a self signed cert at startup.

**Comment by sachinmsft** [comment]
Thanks @brancz . closing the issue now.

**Comment by sachinmsft** [comment]
> When no cert is specified but a secure listen address is passed as a flag then kube rbac proxy generates a self signed cert at startup. That’s what kube prometheus does.

If kube rbac proxy is using self signed cert then how Prometheus is authenticating the kube-rbac-proxy server. ?

**Comment by brancz** [comment]
In kube prometheus the default is to skip cert issues. TLS is also only about transport security, authentication happens using the service account token.

**Comment by sachinmsft** [comment]
> In kube prometheus the default is to skip cert issues. TLS is also only about transport security, authentication happens using the service account token.

Yes, I completely understand the authentication part. I still have doubt about TLS security. Is there any reason to have default as to skip the cert issues. In this case any other server can respond with its self signed cert and client (Prometheus) will assume that it is talking to right target but actually it is not. How we are solving these problems?

**Comment by brancz** [comment]
Unfortunately there is not “the” solution to TLS provisioning. There are many but there is not one built into kube so we don’t want to force some solution onto people. We use open shift mechanisms in our downstream use for this for example, but it’d be awesome if someone wanted to contribute cert manager support on kube prometheus for example.
