### ISSUE TITLE
Protection in case of attacker obtaining full control over a Pod 

### ISSUE THREAD

**Issue by ddysher** [brancz/kube-rbac-proxy#68]
Hi

Thanks for the great tool.  After experimenting with the project, there's one thing i'm not quite sure about.  IIUC, kube-rbac-proxy will run as a reverse proxy alongside with the component being protected. If an attacker obtain full control over a Pod (e.g. Prometheus), then it can still use the token inside the pod to access other endpoints (e.g. kube-state-metrics), in which case, the information is leaked anyway.  Is there anything I'm missing here? or maybe this introduction only refers to Pods apart from Prom..
> I developed this proxy in order to be able to protect Prometheus metrics endpoints. In a scenario, where an attacker might obtain full control over a Pod, that attacker would have the ability to discover a lot of information about the workload as well as the current load of the respective workload.

**Comment by brancz** [comment]
You're correct in some regard, although it doesn't really have anything to do with kube-rbac-proxy. This is the case for any Prometheus pod that gets compromised, or even further, if credentials get compromised, then anyone can impersonate the entity the credentials were issued for. In regard to ServiceAccount tokens, there is one thing that improves the situation, which is audience scoped tokens. With those each token would have a scope, and they can only be used for exactly that scope, so if that token gets compromised, it can only do what it was issued for (essentially limiting blast radius).

Let me know if there is anything else I can answer :)

**Comment by ddysher** [comment]
Thanks @brancz, that helps :)
