### ISSUE TITLE
k8s 1.16 authenticate fialed

### ISSUE THREAD

**Issue by helios741** [brancz/kube-rbac-proxy#69]
I use kube-rbac-proxy as the sidecar of node-expoter,deployed in 1.16 k8s cluster.The following problem appears:

**kubectl logs node-exporter-9g5h7 -f kube-rbac-proxy**
```shell
E0506 10:47:52.120746   39528 auth.go:218] Unable to authenticate the request due to an error: Post https://10.42.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0506 10:48:07.124592   39528 auth.go:218] Unable to authenticate the request due to an error: Post https://10.42.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0506 10:48:22.121446   39528 auth.go:218] Unable to authenticate the request due to an error: Post https://10.42.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0506 10:48:37.122947   39528 auth.go:218] Unable to authenticate the request due to an error: Post https://10.42.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
E0506 10:48:52.125219   39528 auth.go:218] Unable to authenticate the request due to an error: Post https://10.42.0.1:443/apis/authentication.k8s.io/v1beta1/tokenreviews: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc.cluster.local."
```

The image used is kube-rbac-proxy: v0.3.0.

clusterrole and culsterrolebinding are also correct.

apiserver's runtime-config parameter also includes authentication.k8s.io/v1beta1=true.

This configuration is good in a 1.8 cluster.

May I know what is the reason

**Comment by helios741** [comment]
update: 
I can update the image to v0.5, what is the reason?

**Comment by brancz** [comment]
Definitely use the latest version available :) 

The error doesn't seem like it's related to kube-rbac-proxy though, but rather something about your cluster setup.

**Comment by helios741** [comment]
@brancz

**Comment by helios741** [comment]
@brancz 
The 0.3.1 image I used is fine.
Is it because of this: [0.3.1 CHANGELOG](https://github.com/brancz/kube-rbac-proxy/blob/master/CHANGELOG.md#031--2018-06-20)
Do you need to see the configuration of my cluster?

**Comment by brancz** [comment]
As yes seems like it. Just upgrade to latest :) it seems it was solved in 0.3.1

**Comment by helios741** [comment]
@brancz 
Can you tell me what caused the authentication failure?
thanks~

**Comment by brancz** [comment]
It was a bug in the go runtime. I would have to dig that up myself I don’t know off the top of my head.

**Comment by ibihim** [comment]
I will it close as stale. Feel free to reopen, if it is still an issue.
