### ISSUE TITLE
Request client certificates

### ISSUE THREAD

**Issue by nabokihms** [brancz/kube-rbac-proxy#82]
Hello. First of all, thank you for this proxy. It works like a charm. 

I have a problem with that there are no client certificates in the request. The problems seem to be related to server tls configuration. I think we need to change tls config option `ClientAuth` to `RequestClientCert` (default value is `NoClientCert`).
```
srv.TLSConfig.ClientAuth = tls.RequestClientCert
```
The main idea behind this is to extract every client cert and validate it using [x509 authenticator](https://github.com/kubernetes/kubernetes/blob/4d182cec03b880b77fb4879793302dfb3663a281/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go#L86) on the application side.

[Related PR](https://github.com/kubernetes/kubernetes/pull/6190).
Please forgive me if I get it wrong.

**Comment by simonpasquier** [comment]
Thanks for the report and sorry for the late reply! I did a quick test and I agree that we should be setting `ClientAuth: tls.RequestClientCert` [here](https://github.com/brancz/kube-rbac-proxy/blob/e4b31758aedb3d29d8f50d615828401a30d28c1e/main.go#L259). The fix itself is very simple but adding a test case is more involved. If someone wants to have a look, they're welcome :)

cc @s-urbaniak for awareness.

**Comment by nabokihms** [comment]
I feel like I can give it a try if you do not mind.

**Comment by s-urbaniak** [comment]
@nabokihms generally the addition of `RequestClientCert` makes sense to me, but out of curiosity to understand why we need that option, do you also want to contribute a client-cert based authenticator in kube-rbac-proxy as well?

**Comment by nabokihms** [comment]
The client-cert based authenticator is already in the code.

Actually, [this authenticator](https://github.com/brancz/kube-rbac-proxy/blob/master/pkg/authn/delegating.go#L57) is a combination of various authenticators.

Look [here](https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go#L59). The `New` method shows exactly how it combines authenticators and which authentication types you can use.

So, two thing you need to do to make client-cert based authenticator works:
* Add `srv.TLSConfig.ClientAuth = tls.RequestClientCert`
* Specify `--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` flag for kube-rbac-proxy instance.

**Comment by nabokihms** [comment]
I forked this proxy and tested it (I think it was a year ago). In our Kubernetes clusters, we use both tokens and certs.

**Comment by s-urbaniak** [comment]
Ahh, ok i was always under the impression that the delegating authenticator just does the token review. Yes, this makes perfect sense to me now :+1: Indeed, that would be a great contribution!
