### ISSUE TITLE
Move CI to github actions

### ISSUE THREAD

**Issue by paulfantom** [brancz/kube-rbac-proxy#93]
It might be beneficial to move to GitHub Actions as stated in https://github.com/brancz/kube-rbac-proxy/pull/92#issuecomment-704926156

**Comment by markkuleppala** [comment]
Hello! I could work on this issue.

**Comment by paulfantom** [comment]
Thanks! :100:

**Comment by markkuleppala** [comment]
I'm opening a PR soon. For some reason part of the e2e tests fail, but otherwise the build file is complete.

**Comment by s-urbaniak** [comment]
i think we're done here :-) closing out as the PRs merged quite some time ago.
