### ISSUE TITLE
Is there a plan to do a patch release with support to use `--ignore-paths`  ?

### ISSUE THREAD

**Issue by hectorj2f** [brancz/kube-rbac-proxy#97]
I pulled v0.7.0 but it doesn't support the flag `--ignore-paths`. Would you release a patch release ?

**Comment by brancz** [comment]
cc @simonpasquier @paulfantom anyone wants to cut a release? :)

**Comment by hectorj2f** [comment]
Yes, that would be great!

**Comment by hectorj2f** [comment]
@brancz Is there any way I could help to cut a release here ?
